version: '3'
services:
  back:
    image: syd-back:0.1
    build:
      context: ./back
      dockerfile: Dockerfile.dev
    ports:
      - "8000:8000"
  
  front:
    image: syd-front:0.1
    build:
      context: ./front
      dockerfile: Dockerfile.dev
    ports:
      - "8080:8080"
